n = input('Digite uma variável: ')
print('Qual o tipo primitivo?' , type(n))
print('É numérico?' , n.isnumeric())
print('É alfabetico?' , n.isalpha())
print('É alfanumérico?' , n.isalnum())
print('Tem caractere maiusculo?' , n.isupper())
print('Tem caractere minúsculo?' , n.islower())
print('Está capitalizada?' , n.istitle())
print('Os caracteres são decimais?' , n.isdecimal())
print('Os caracteres são digitos?' , n.isdigit())
print('Os caracteres são imprimiveis?' , n.isprintable())
print('Os caracteres são espaços?' , n.isspace())
