n = float(input('Digite um número: '))
print(f'{n} vezes 2 é {n*2:.3f}')
print(f'{n} vezes 3 é {n*3:.3f}')
print(f'{n} vezes 4 é {n*4:.3f}')
print(f'{n} vezes 5 é {n*5:.3f}')
print(f'{n} vezes 6 é {n*6:.3f}')
print(f'{n} vezes 7 é {n*7:.3f}')
print(f'{n} vezes 8 é {n*8:.3f}')
print(f'{n} vezes 9 é {n*9:.3f}')
print(f'{n} vezes 10 é {n*10:.3f}')